<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Core\Framework\Framework.csproj" />
      <ProjectReference Include="..\Questions.Application\Questions.Application.csproj" />
      <ProjectReference Include="..\Questions.Contracts\Questions.Contracts.csproj" />
      <ProjectReference Include="..\Questions.Domain\Questions.Domain.csproj" />
      <ProjectReference Include="..\Questions.Infrastructure.Postgres\Questions.Infrastructure.Postgres.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    </ItemGroup>

</Project>
